[language-server.vscode-eslint-language-server]
command = "/Users/makoto/.asdf/shims/vscode-eslint-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = false }
format = { enable = false }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
problems = { shortenToSingleLine = false }

[language-server.vscode-eslint-language-server.config.workingDirectory]
mode = "auto"

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true


[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

