[language-server.jdtls]
command = "sh"
args = [
  "-c",
  '''
  exec jdtls --jvm-arg=-javaagent:"$HOME/.local/lib/lombok.jar"
  '''
]

[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = false }
format = { enable = false }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
problems = { shortenToSingleLine = false }

[language-server.vscode-eslint-language-server.config.workingDirectory]
mode = "auto"

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier" }

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "pnpm prettier" }

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier" }

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier" }


[[language]]
name = "json"
formatter = { command = "prettier" }

[[language]]
name = "css"
formatter = { command = "prettier" }

[[language]]
name = "html"
formatter = { command = "prettier" }

[[language]]
name = "markdown"
formatter = { command = "prettier" }

