alias tmux='tmux -2'
alias tiga='tig --all'
alias tigs='tig status'
alias mytig='tig --author="$(git config user.email)"'
alias mytiga='tig --all --author="$(git config user.email)"'
alias g='git'
alias ls='ls --color'
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias grep='ugrep'
